### ISSUE TITLE
sidecar does not see any dotnet processes on osx docker

### ISSUE THREAD

**Issue by tommyk** [joe-elliott/netcore-kubernetes-profiling#2]
i can not see any dotnet processes from the sidecar when running
```
ps aux
```
on the attached sidecar container.  any ideas?

here is the docker info
![image](https://user-images.githubusercontent.com/27677/59055013-e617c200-8862-11e9-83d2-15e2198b7ec1.png)

**Comment by joe-elliott** [comment]
All of the techniques are dependent on setting the [shareProcessNamespace](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) field to true.  This became beta and therefore available by default in k8s 1.12

In k8s before 1.12 (I see you have 1.10) you would have to pass flags to turn on this feature b/c it would have been considered alpha:  https://v1-10.docs.kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

Also, I don't know much about the docker/k8s integration.  I tend to use [minikube](https://kubernetes.io/docs/setup/minikube/) locally.  I am unsure if you are even able to pass the required flags to get this to work.
