### ISSUE TITLE
Unable to find package

### ISSUE THREAD

**Issue by mayconbeserra** [joe-elliott/netcore-kubernetes-profiling#5]
Hi @joe-elliott ,

I get the error unable to locate the package ```E: Unable to locate package bpfcc-tools``` when building the sidecar container.

Is the package name correct?

reference:
https://github.com/joe-elliott/netcore-kubernetes-profiling/blob/66e4ec75cea42bf255c80707f995183b73c65ea6/images/Dockerfile#L11

Thank you

**Comment by joe-elliott** [comment]
Thanks for pointing this out.  I was able to reproduce your issue locally which prompted me to re-read the debian repository documentation.  I had used this line:
```
echo deb http://cloudfront.debian.net/debian testing main >> /etc/apt/sources.list
```
to add a repository that had bpfcc-tools, but according to the docs the "testing" repo drifts as releases are cut. 

Changing it to 
```
echo deb http://cloudfront.debian.net/debian sid main >> /etc/apt/sources.list
```
locally is working.  This seems to be backed up by this: https://packages.debian.org/sid/misc/bpfcc-tools

Will push a fix shortly.
